config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :balances, only: [ :index, :new, :show, :create, :edit, :update]
  resources :collections do 
    resources :items , only: [ :new, :create] do
      resources :transactions, only: [ :new, :create]
    end
  end
  resources :items, only: [:show, :destroy, :edit, :update]
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @transactions = policy_scope(Transaction)
    @collections = policy_scope(Collection)
    @items = policy_scope(Item)
  end

  def new
    @collection = Collection.new
    authorize @collection
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    @collection.save
    authorize @collection
    redirect_to collections_path
  end

  def show
    @transactions = policy_scope(Transaction)
    @collection = Collection.find(params[:id])
    @items = policy_scope(Item)
    authorize @collection
  end

  def edit
    @collection = Collection.find(params[:id])
    authorize @collection
  end

  def update
    @collection = Collection.find(params[:id])
    @collection.update(collection_params)
    authorize @collection
    redirect_to collection_path(@collection)
  end

  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    authorize @collection
    redirect_to collections_path, notice: 'Collection is deleted.'
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :user)
  end
end

app/views/collections/edit.html.erb
<%# form box %>
<div class="relative mt-5 ">

  <div class="absolute top-5 left-60 font-sans text-gray-600 font-medium">
    <%= link_to "< Back ", collections_path, style:"text-decoration: none; color: inherit;"%>
  </div>

  <div class="grid bg-white rounded-lg shadow-xl w-1/2 m-auto">

    <div class="flex justify-center py-4">
      <div class="flex bg-gray-200 rounded-full p-2 border-2 border-gray-300">
        <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path></svg>
      </div>
    </div>

    <div class="flex justify-center">
      <div class="flex">
        <h1 class="text-gray-600 font-bold text-xl">Edit Collection</h1>
      </div>
    </div>

    <%= simple_form_for(@collection) do |f| %>

    <div class="grid grid-cols-1 mt-5 mx-7">

      <label class="uppercase text-xs text-gray-500 font-semibold">Collection name</label>
      <%= f.input :name, label: '', input_html: { class: ' w-full py-2 px-3 rounded-lg border-2 border-gray-300 mt-1 focus:outline-none focus:ring-2 focus:ring-gray-600 focus:border-transparent'}%>
    </div>


    <div class="grid grid-cols-1 pt-5 pb-5 px-72">
      <%= f.button :submit, "Update", class: "bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl font-medium text-white px-4 py-2" %>
    </div>
    <% end %>

  </div>


</div>

app/views/collections/index.html.erb
<div class="flex justify-between w-screen mx-0 pl-0">

  <div class="profile-box shadow-sm h-screen flex flex-col content-center font-sans w-1/6 bg-gray-100">
    <div class="flex flex-col m-auto">
      <div class="pb-4 self-center">
        <%= image_tag "https://i.pinimg.com/564x/51/07/75/510775920002ed607ff0a5582932214a.jpg", class: "w-24 h-24 rounded-full border-gray-400" %>
      </div class="">
      <div class="text-base font-medium text-gray-600 text-center pb-4"><%= current_user.email %></div>

      <div class="text-base font-bold text-gray-600 text-center pt-6">
      <% @counter = 0 %>
        <% @items.each do |item| %>
          <% @counter += 1 if User.find(Collection.find(item.collection_id).user_id) == current_user %>
        <% end %>
        <%= @counter %>
      </div>
      <div class="text-sm text-gray-400 text-center pb-6">ITEMS</div>
      <div class="text-base font-bold text-gray-600 text-center pt-6">
        <% @transaction_counter = 0 %>
        <% @transactions.each do |transaction| %>
          <% @transaction_counter += 1 if current_user == User.find(transaction.seller_id) || current_user == User.find(transaction.buyer_id) %>
        <% end %>
        <%= @transaction_counter %>
      </div>
      <div class="text-sm text-gray-400 text-center pb-6">TRANSACTIONS</div>

      <% if current_user.balance.nil? %>
        <div class="pt-8">
        <%= link_to "Airdrop", balances_path, method: :post, class: "bg-green-500 hover:bg-green-700 rounded-xl shadow-xl font-medium text-white px-4 py-2" %>
        </div>
      <% else  %>
        <div class="text-base font-bold text-gray-600 text-center pt-6 mb-1">
        <i class="fab fa-ethereum text-gray-500"></i>
        <%= current_user.balance.amount %>
        </div>
        <div class=" text-sm text-gray-400 text-center mb-1">BALANCE</div>
        <%= link_to "Top Up", edit_balance_path(current_user.balance.id), class: "bg-gray-400 hover:bg-gray-500 text-sm rounded-xl shadow-xl font-medium text-center text-white px-3 py-1", style:"text-decoration: none;"%>
      <% end %>

    </div>

  </div>

  <div class="show-box w-5/6 pl-4">
    <div class="collections m-4">
      <div class=" flex justify-between">
        <div class="text-gray-500 font-bold text-xl mx-4">Collections</div>
        <div class="add-btn text-green-500 font-bold texl-2xl"><%= link_to "+ new collection", new_collection_path, style:"text-decoration: none; color: inherit;"%></div>
      </div>

      <%# cards %>
      <div class="list-cards grid grid-cols-4 gap-4 p-10">

        <% current_user.collections.each do |collection| %>
          <div class="grid">
            <%= link_to collection_path(collection) do%>
              <div class="list-card relative flex align-between justify-self-center bg-gradient-to-br from-green-400 to-green-500 hover:bg-green-700 w-52 h-52 rounded-3xl">
                <div class="absolute  inset-x-0 bottom-2 px-4">
                  <p class="list-id m-3 text-3xl font-sans text-gray-200">#</p>
                  <p class="m-3 font-sans text-gray-200 text-xl font-extralight"><%=collection.name %></p>
                </div>
                <div class="font-sans text-gray-200 text-xl font-thin object-right absolute top-4 right-5">
                  <%= link_to 'x', collection_path(collection), method: :delete %>
                </div>
                <div class="edit-btn absolute top-4 left-5">
                  <%= link_to edit_collection_path(collection) do %>
                    <i class="far fa-edit text-gray-200"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>

    <%# transaction history %>

    <div class="transactions flex flex-col w-full m-4">
      <div class="text-gray-500 font-bold text-xl mx-4">User Transaction History</div>

      <div class="table font-sans p-4 text-center rounded-xl border-green-500 border-solid w-11/12">
        <div class="table-name grid grid-cols-5 gap-4 mx-4 mt-4 font-bold text-base text-green-500">
          <div>Item ID</div>
          <div>FROM</div>
          <div>TO</div>
          <div>Price</div>
          <div>Time</div>
        </div>

      <% @transactions.each do |transaction| %>
        <% if current_user == User.find(transaction.seller_id) || current_user == User.find(transaction.buyer_id) %>
            <div class="table-info grid grid-cols-5 gap-4 mx-4 mt-4 font-medium text-sm text-gray-500 bg-gray-100">
              <div><%= @item = Item.find(transaction.item.id).name %></div>
              <div><%= @email = User.find(transaction.seller_id).email %></div>
              <div><%= @email = User.find(transaction.buyer_id).email %></div>
              <div><%= transaction.item.price %></div>
              <div><%= transaction.created_at %></div>
            </div>
        <% else %>
            <div>
            </div>
        <% end %>
      <% end %>



      </div>
    </div>
  </div>

</div>



<h1><%= link_to "Give me some airdrops(update)", balances_path, method: :post %></h1>

app/views/collections/new.html.erb
<div class="relative mt-5">

  <div class="absolute top-5 left-60 font-sans text-gray-600 font-medium">
    <%= link_to "< Back ", collections_path, style:"text-decoration: none; color: inherit;"%>
  </div>

  <%# form box %>
  <div class="grid bg-white rounded-lg shadow-xl w-1/2 m-auto ">

    <div class="flex justify-center py-4">
      <div class="flex bg-gray-200 rounded-full p-2 border-2 border-gray-300">
        <svg class="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"></path></svg>
      </div>
    </div>

    <div class="flex justify-center">
      <div class="flex">
        <h1 class="text-gray-600 font-bold text-xl">New Collection</h1>
      </div>
    </div>

    <%= simple_form_for(@collection) do |f| %>

    <div class="grid grid-cols-1 mt-5 mx-7">

      <label class="uppercase text-xs text-gray-500 font-semibold">Collection name</label>
      <%= f.input :name, label: '', input_html: { class: ' w-full py-2 px-3 rounded-lg border-2 border-gray-300 mt-1 focus:outline-none focus:ring-2 focus:ring-gray-600 focus:border-transparent'}%>
    </div>


    <div class="grid grid-cols-1 pt-5 pb-5 px-72">
      <%= f.button :submit, "Create", class: "bg-gray-500 hover:bg-gray-700 rounded-lg shadow-xl text-center font-medium text-white px-4 py-2" %>
    </div>
    <% end %>

  </div>

</div>

app/views/collections/show.html.erb
<div class=" flex justify-between w-screen mx-0 pl-0">

  <div class="profile-box shadow-sm h-screen flex flex-col content-center font-sans w-1/6 bg-gray-100">
    <div class="flex flex-col m-auto">
      <div class="pb-4 self-center">
        <%= image_tag "https://i.pinimg.com/564x/51/07/75/510775920002ed607ff0a5582932214a.jpg", class: "w-24 h-24 rounded-full border-gray-400" %>
      </div class="">
      <div class="text-base font-medium text-gray-600 text-center pb-4"><%= current_user.email %></div>

      <div class="text-base font-bold text-gray-600 text-center pt-6">
        <% @counter = 0 %>
        <% @items.each do |item| %>
          <% @counter += 1 if User.find(Collection.find(item.collection_id).user_id) == current_user %>
        <% end %>
        <%= @counter %>
      </div>
      <div class="text-sm text-gray-400 text-center pb-6">ITEMS</div>
      <div class="text-base font-bold text-gray-600 text-center pt-6">
        <% @transaction_counter = 0 %>
        <% @transactions.each do |transaction| %>
          <% @transaction_counter += 1 if current_user == User.find(transaction.seller_id) || current_user == User.find(transaction.buyer_id) %>
        <% end %>
        <%= @transaction_counter %>
      </div>
      <div class="text-sm text-gray-400 text-center pb-6">TRANSACTIONS</div>

      <% if current_user.balance.nil? %>
        <div class="pt-8">
        <%= link_to "Airdrop", balances_path, method: :post, class: "bg-green-500 hover:bg-green-700 rounded-xl shadow-xl font-medium text-white px-4 py-2" %>
        </div>
      <% else  %>
        <div class="text-base font-bold text-gray-600 text-center pt-6 mb-1">
          <i class="fab fa-ethereum text-gray-500"></i>
          <%= current_user.balance.amount %>
        </div>
        <div class=" text-sm text-gray-400 text-centermb-1 self-center">BALANCE</div>
        <div class="self-center">
          <%= link_to "Top Up", edit_balance_path(current_user.balance.id), class: "bg-gray-400 hover:bg-gray-500 text-sm rounded-xl shadow-xl font-medium text-center text-white px-4 py-1", style:"text-decoration: none;"%>
        </div>
      <% end %>
      <div class="mt-8 self-center">
        <%= link_to "Create", new_collection_item_path(@collection), class: "bg-green-500 hover:bg-green-700 text-sm rounded-xl shadow-xl font-medium text-white px-4 py-2 text-center", style:"text-decoration: none;" %>
      </div>
    </div>

  </div>

  <div class="show-box w-5/6 pl-4">

    <div class="items mt-4">
      <div class="font-sans text-gray-500 font-medium mx-4 my-2">
      <%= link_to "< Back ", collections_path, style:"text-decoration: none; color: inherit;"%>
    </div>

      <div class="text-gray-500 font-bold text-xl mx-4"><%= @collection.name %></div>

      <div class="item-cards grid grid-cols-3 gap-4 px-4 justify-items-center mb-6">
        <% @collection.items.each do |item|%>
        <div>
          <%= link_to item_path(item), style:"text-decoration: none; color: inherit;" do %>
          <div class="card relative w-64 h-80 bg-white rounded-2xl m-2 font-sans">
            <div class="favourite-btn absolute top-3 right-3">
              <p>&hearts;<p>
            </div>
            <div class="item w-full flex flex-col justify-between content-between h-full m-auto">
              <div class="item-image w-44 h-44 justify-self-center m-auto">
                <img class="object-cover w-full h-full rounded" src="<%= item.img_url %>" alt="">
              </div>

              <div class="item-info flex justify-between mx-4 text-sm">
                <div class="id bg-green-500 text-white text-xs rounded-xl px-3 h-4">#434<%= item.id %></div>
                <div class="name flex flex-col ">
                  <div><%= item.name %></div>
                </div>
              </div>

              <div class="item-record flex justify-around h-8 mx-3 my-2">
                <div class="text-xs text-gray-400"><%= item.created_at %></div>
                <div class=" text-xs">
                  <i class="fab fa-ethereum text-gray-500"></i>
                  <span><%= item.price %></span>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

    <%# transaction history %>
  </div>

</div>