config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :balances, only: [ :index, :new, :show, :create, :edit, :update]
  resources :collections do 
    resources :items , only: [ :new, :create] do
      resources :transactions, only: [ :new, :create]
    end
  end
  resources :items, only: [:show, :destroy, :edit, :update]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :collection
  has_many :transactions, dependent: :destroy

  # validates :name, presence: true, uniqueness: true
  # validates :species, presence: true, inclusion: { in: %w(normal, fire, water, grass, flying, fighting, poison, electric, ground, rock, psychic, ice, bug, ghost, steel, dragon, dark, fairy)}
  # validates :img_url, presence: true
  # validates :description, presence: true, length: { minimum: 10 }
  # validates :price, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @collection = Collection.find(params[:collection_id])
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @collection = Collection.find(params[:collection_id])
    @item.collection = @collection
    @item.save
    authorize @item
    redirect_to collection_path(@collection)
  end

  def show
    @transactions = policy_scope(Transaction)
    @collections = policy_scope(Collection)
    @items = policy_scope(Item)
    @item = Item.find(params[:id])
    authorize @item
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    authorize @item
    redirect_to item_path(@item)
  end

  def destroy
    @item = Item.find(params[:id])
    @collection = @item.collection
    @item.destroy
    redirect_to collection_path(@collection.id)
    authorize @item
  end

  private

  def item_params
    params.require(:item).permit(:name, :species, :img_url, :description, :price, :collection_id, :favorite)
  end


end

app/views/items/edit.html.erb
<div class="relative w-full grid">
  <div class="absolute top-14 left-20 font-sans text-gray-600 font-medium">
    <%= link_to "< Back ", collections_path%>
  </div>

  <div class="w-1/3 justify-self-center mt-4">
    <h1 class="text-2xl font-bold text-green-500 mb-5 text-center">Edit Item</h1>
    <%= simple_form_for([@collection, @item]) do |f| %>
    <div>
      <%= f.input :name %>
    </div>
    <div>
      <%= f.input :species %>
    </div>
    <div>
      <%= f.input :description %>
    </div>
    <div>
      <%= f.input :img_url %>
    </div>
    <div>
      <%= f.input :price %>
    </div>

    <div class="w-full flex justify-center ">
      <%= f.button :submit ,class:"bg-green-500 hover:bg-green-700 text-white rounded-xl shadow-xl px-4 py-2"%>
    </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="relative w-full grid">
  <div class="absolute top-14 left-20 font-sans text-gray-500 font-medium">
   <%= link_to "< Back ", collections_path%>
  </div>

  <div class="w-1/3 justify-self-center mt-4 ">
    <h1 class="text-2xl font-bold text-green-500 mb-4 text-center">New Item</h1>
    <%= simple_form_for([@collection, @item]) do |f| %>
    <div>
      <%= f.input :name %>
    </div>
    <div>
      <%= f.input :species %>
    </div>
    <div>
      <%= f.input :description %>
    </div>
    <div>
      <%= f.input :img_url %>
    </div>
    <div>
      <%= f.input :price %>
    </div>

    <div class="w-full flex justify-center ">
      <%= f.button :submit ,class:"bg-green-500 hover:bg-green-700 text-white rounded-xl shadow-xl px-4 py-2"%>
    </div>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class=" relative w-full h-full flex flex-col align-center m-auto">
  <div class="absolute top-14 left-24 font-sans text-gray-600 font-medium">
  <%= link_to "< Back ", collection_path(@item.collection_id)%>
  </div>

  <div class="card mt-4 w-4/6 h-5/6 shadow-sm self-center rounded-xl">

    <div class="item-info w-full h-20 flex self-center justify-center mt-6">

      <div class="item-name-type w-2/5 h-32 mx-3 my-2 flex justify-between">
        <div class="id w-28 h-8 bg-green-500 rounded-xl flex justify-center ">
          <p class="self-center text-white">#434<%= @item.id  %></p>
        </div>

        <div class="owner-email mr-3 text-sm text-gray-500">
          <div>Owner</div>
          <div>
            <%= User.find(Collection.find(@item.collection_id).user_id).email %>
          </div>
        </div>

      </div>

      <div class="item-price w-2/5 h-32 my-2 ml-4">
        <div class="w-full h-1/3 flex justify-between " >
          <div class="price w-32 h-10 bg-white flex">
            <div class="self-center text-xl">
              <i class="fab fa-ethereum text-gray-500"></i>
              <span class="text-gray-700"><%= @item.price %></span>
            </div>
          </div>

          <% @collection = Collection.find(@item.collection_id) %>
          <% if @collection.user_id == current_user.id %>
            <div class="bg-green-500 hover:bg-green-700 rounded-xl shadow-xl font-medium text-white px-4 py-2">Your Item
            </div>
          <% else %>
            <div class="pt-8">
            <%= link_to "Buy", new_collection_item_transaction_path(@item.collection_id, @item.id), class: "bg-green-500 hover:bg-green-700 rounded-xl shadow font-medium text-white px-4 py-2" %>
            </div>
          <% end %>
        </div>

        <div class="date content-end text-gray-400">
          <p><%= @item.created_at %></p>
        </div>

      </div>
    </div>

    <div class="item-detail w-11/12 h-4/5 flex self-center justify-center mb-6">

      <div class="img w-1/2 h-full mx-4 my-3 flex justify-center">
        <img class="rounded-3xl shadow-lg object-cover p-2 h-full self-center" src="<%= @item.img_url %>" alt="">
      </div>

      <div class="description flex flex-col w-1/2 h-full mx-4 my-3">
        <div class="name h-10 bg-white flex">
          <p class="self-center text-gray-500 text-base mr-10">Name</p>
          <span class="text-green-500 self-center"><%= @item.name %></span>
        </div>

        <div class="type h-10 bg-white flex">
          <p class="self-center text-gray-500 text-base mr-10">Type</p>
          <span class="text-green-500 self-center"><%= @item.species %></span>
        </div>

        <div class="about bg-white flex mt-2">
          <p class="self-center text-gray-500 text-xl">About</p>
        </div>

        <div class="description-text border border-solid rounded-xl border-gray-300 text-gray-500 w-full h-48 my-2">
          <p class="p-2"><%= @item.description %></p>
        </div>

        <div class="btns mt-3">
           <% @collection = Collection.find(@item.collection_id) %>
            <% if @collection.user_id == current_user.id %>
              <div class="text-gray-700">
                <%= link_to "Edit", edit_item_path(@item)%>
              </div>

              <div class="text-gray-700">
                <%= link_to "Delete", item_path(@item), method: :delete %>
              </div>
            <% else %>
              <div></div>
            <% end %>
        </div>

      </div>


    </div>
  </div>

  <div class="transactions w-4/6 flex flex-col mt-6 self-center">
    <div class="text-gray-500 font-bold text-xl pt-4">Item's Transaction History</div>
    <div class="table font-sans px-4 text-center rounded-xl border-green-500 border-solid w-11/12">
      <div class="table-name grid grid-cols-5 gap-4 mx-4 mt-4 font-bold text-base text-green-500">
        <div>Item ID</div>
        <div>FROM</div>
        <div>TO</div>
        <div>Price</div>
        <div>Time</div>
      </div>

  <% @transactions.each do |transaction| %>
        <% if transaction.item.id == params[:id].to_i  %>
          <div class="table-info grid grid-cols-5 gap-4 mx-2 mt-4 font-medium text-sm text-gray-500 bg-gray-100">
            <div><%= @item_name = Item.find(transaction.item.id).name %></div>
            <div><%= @email = User.find(transaction.seller_id).email %></div>
            <div><%= @email = User.find(transaction.buyer_id).email %></div>
            <div><%= transaction.item.price %></div>
            <div><%= transaction.created_at %></div>
          </div>        
        <% end %>
    <% end %>

  </div>

 </div>