config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :balances, only: [ :index, :new, :show, :create, :edit, :update]
  resources :collections do 
    resources :items , only: [ :new, :create] do
      resources :transactions, only: [ :new, :create]
    end
  end
  resources :items, only: [:show, :destroy, :edit, :update]
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController



  def new
    @item = Item.find(params[:item_id])
    @collection_id = @item.collection_id
    @transaction = Transaction.new
    authorize @transaction

  end

  def create

    #找到交易物品，创立新的交易
    @item = Item.find(params[:item_id])
    @buyer_id = current_user.id
    @transaction = Transaction.new( item_id: @item.id, buyer_id: @buyer_id)

    # 换buyer的balance，也就是current_user balance
    @balance = Balance.find(@buyer_id)
    @balance.amount -= @transaction.item.price
    @balance.update(amount: @balance.amount)
    
    #换seller的bal1ance
    @seller_id = @item.collection.user_id
    @balance1 = Balance.find(@seller_id)
    @balance1.amount = @balance1.amount + @transaction.item.price
    @balance1.update(amount: @balance1.amount)
   
    #物品进行置换
    @item.collection_id = current_user.collections[0].id
    @item.save

    #存item, buyer, seller的id, 交易保存
    
    @transaction.seller_id = @seller_id
    @transaction.save
  
    authorize @transaction
    redirect_to item_path(@item)

  end

  def update
    @transaction = Transaction.find(params[:id])
    @transaction.update(transaction_params)
    authorize @transaction
    redirect_to collections_path
  end

private

  def transaction_params
    params.require(:transaction).permit(:item_id, :buyer_id, :seller_id)
  end

end

app/views/transactions/new.html.erb
<div class="relative mt-5 ">

  <div class="absolute top-4 left-60 font-sans text-gray-600 font-medium">
    <%= link_to "< Back ", collections_path, style:"text-decoration: none; color: inherit;"%>
  </div>

  <div class=" w-full h-full bg-transparent mt-20">

    <div class="card w-2/5 h-4/5 flex flex-row m-auto border-none bg-transparent">

      <div class="item-info flex flex-col justify-between w-3/5 bg-gray-100 shadow rounded-l-lg">
        <div class="info-text flex flex-col justify-between pt-4 pl-4">
          <div class="id bg-green-500 text-white text-xs rounded-xl px-3 h-4 w-20">#434<%= @item.id %></div>
          <div class="flex mt-2 ">
            <div class="text-gray-500 ">NAME </div>
            <div class="text-green-500 pl-2"><%= @item.name %></div>
          </div>
          <div class="flex mt-2 ">
            <div class="text-gray-500 ">TYPE </div>
            <div class="text-green-500 pl-2"><%= @item.species %></div>
          </div>
        </div>
        <div class="item-image self-center w-44 h-44 mb-10">
          <img class="object-cover w-full h-full rounded" src="<%= @item.img_url %>" alt="">
        </div>
      </div>

      <div class="checkout-box flex flex-col justify-between w-2/5 bg-green-500 text-white shadow rounded-r-lg">
        <div class="cart-title text-white font-sans font-medium text-xl px-2 pt-3">CART</div>
        <div class="checkout-details h-3/5 pt-32">
          <div>
            <div class="flex justify-between mt-2 text-gray-100 items-center px-2">
              <div class="text-xs">CURRENT BALANCE </div>
              <div class="pl-2 text-xs">
                <i class="fab fa-ethereum text-gray-200"></i>
                <%= current_user.balance.amount %>
              </div>
            </div>
            <div class="flex justify-between my-2 text-gray-100 items-center px-2">
              <div class="text-xs">SUBTOTAL </div>
              <div class="pl-2 text-xs">
                <i class="fab fa-ethereum text-gray-200"></i>
                <%= @item.price %>
              </div>
            </div>
            <hr style="width:100%", size="2", color=white>
          </div>
        </div>

        <div class="checkout-btns flex flex-col pl-28 pt-10">
          <%= link_to "Top Up", edit_balance_path(current_user.balance.id), class: "bg-gray-400 hover:bg-gray-500 text-xs rounded-xl shadow-xl font-medium text-center text-white py-1 w-24", style:"text-decoration: none;"%>
          <div class="bg-gray-100 hover:bg-gray-300 text-xs rounded-xl shadow-xl font-medium text-center text-green-500 py-1 w-24 my-2", style="text-decoration: none;">
            <%= link_to " CHECKOUT > ",  collection_item_transactions_path(@collection_id, @item), method: :post %>
          </div>
        </div>
      </div>

    </div>
  </div>

  </div>